---
- name: Install vector CentOS 7
  include: centos7.yml
  when: (ansible_facts['distribution_major_version'] == "7" and ansible_distribution == "CentOS")
  tags: vector
- name: Install vector CentOS 8
  include: centos8.yml
  when: (ansible_facts['distribution_major_version'] == "8" and ansible_distribution == "CentOS")
  tags: vector
- name: Install vector Ubuntu
  include: ubuntu.yml
  when: (ansible_distribution == "Ubuntu")
  tags: vector
