---
- name: Install vector
  ansible.builtin.yum:
          name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm"
          state: present
  notify: Start vector service
- name: copy vector config
  ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_folder }}/vector.yaml"
        mode: 0644
- name: copy vector service config
  ansible.builtin.template:
        src: vector_service.j2
        dest: /usr/lib/systemd/system/vector.service
        mode: 0644
  notify: Start vector service
  tags: vector          
