---
- name: Install vector ubuntu
  apt:
   deb: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
   state: present
  become: true
  notify: Start vector service
  tags: vector
- name: copy vector config
  ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_folder }}/vector.yaml"
        mode: 0644
  tags: vector
- name: copy vector service config
  ansible.builtin.template:
        src: vector_service.j2
        dest: /lib/systemd/system/vector.service
        mode: 0644
  notify: Start vector service 
